### ISSUE TITLE
Where is the 'setup.ini' ? 

### ISSUE THREAD

**Issue by abdulbadii** [10sr/pac-cyg#4]
I tried to search but giving error:
```
$ pac-cyg  -Ss rpm
>> repository [main]
awk: fatal: cannot open file `/var/cache/pac-cyg/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin/x86_64/setup.ini' for reading (No such file or directory)
```
How to solve it?

**Comment by 10sr** [comment]
Sorry I haven't had a Cygwin environment for a long time, so I cannot check the problem shortly...
 How about running `pac-cyg -Sy` first?

**Comment by abdulbadii** [comment]
SOLVED !
Thanks a billion !!!
